### ISSUE TITLE
How to Implement

### ISSUE THREAD

**Issue by enijar** [egtoney/JDaeLoader#1]
I'm not a Java dev but your library looks like what I need. 

I need to load a `.dae` file into an Android app. I'm using [Android Studio](https://developer.android.com/studio/index.html) on a Mac.

How do I load this library into my existing project?

I get this following error after importing your library.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.lwjgl.Sys$1.run(Sys.java:72)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:65)
	at org.lwjgl.Sys.loadLibrary(Sys.java:81)
	at org.lwjgl.Sys.<clinit>(Sys.java:98)
	at org.lwjgl.opengl.Display.<clinit>(Display.java:132)
	at ColladaDemo.Window.<init>(Window.java:45)
	at ColladaDemo.ColladaDemo.<init>(ColladaDemo.java:20)
	at ColladaDemo.ColladaDemo.main(ColladaDemo.java:29)
```

**Comment by egtoney** [comment]
From what I can tell it looks like you haven't included LWJGL into your project's library path. This repository doesn't actually use LWJGL so it may be a problem with your project setup.

**Comment by enijar** [comment]
Thanks for the fast reply. I'll try setting up what you have suggested and get back to you.
